import React, { useState, useEffect } from 'react';
import { 
  FileCode, 
  Code2, 
  CheckCircle2, 
  ArrowRight, 
  RotateCw, 
  Copy, 
  Check,
  Cpu,
  Loader2,
  Sparkles,
  Download
} from 'lucide-react';
import { AppState, PlaywrightScript, TestCase } from '../../types';

interface TestScriptWorkspaceProps {
  appState: AppState | null;
  selectedCaseIds: string[];
  onRefresh: (runId: string) => Promise<void>;
  onProceedNext: () => void;
}

const generatePlaywrightScriptForCase = (tc: TestCase): PlaywrightScript => {
  const caseIdClean = tc.case_id.toLowerCase().replace(/-/g, '_');
  const isNegative = tc.case_type?.toUpperCase() === 'NEGATIVE';
  const isBoundary = tc.case_type?.toUpperCase() === 'BOUNDARY';

  const code = `"""
Playwright Automation Test Script: ${tc.case_id}
Title: ${tc.title}
Category: ${tc.case_type} | Feature Area: ${tc.feature_area || 'CFA Application'}
Generated by: Test Script Specialist Agent
"""

import pytest
from playwright.sync_api import Page, expect
from pages.cfa_portal_page import CFAPortalPage


@pytest.mark.playwright
def test_${caseIdClean}(page: Page, target_url: str):
    """
    Test Case ID: ${tc.case_id}
    Scenario: ${tc.title}
    """
    # 1. Initialize Page Object Model
    portal = CFAPortalPage(page, base_url=target_url)
    portal.navigate_to_portal()

    # 2. Execute Scenario Actions
    portal.fill_applicant_form(
        case_id="${tc.case_id}",
        is_negative=${isNegative ? 'True' : 'False'},
        is_boundary=${isBoundary ? 'True' : 'False'}
    )

    # 3. Capture Pre-assertion Evidence Screenshot
    page.screenshot(
        path=f"artifacts/screenshots/${tc.case_id}_EXEC.png",
        full_page=True
    )

    # 4. Scenario Assertions & Verification
    ${isNegative
      ? 'portal.verify_validation_error_displayed()'
      : isBoundary
      ? 'portal.verify_boundary_handling_successful()'
      : 'portal.verify_submission_success()'
    }

    # 5. Dual Screenshot Verification Capture
    page.screenshot(
        path=f"artifacts/screenshots/${tc.case_id}_${isNegative ? 'FAILED' : 'PASSED'}.png",
        full_page=True
    )
`;

  const selectors = [
    `[data-testid="cfa-onboarding-form"]`,
    `[data-testid="${tc.case_id.toLowerCase()}-input"]`,
    `[data-testid="submit-btn"]`,
    isNegative ? `[data-testid="error-alert"]` : `[data-testid="success-banner"]`
  ];

  return {
    test_case_id: tc.case_id,
    filename: `test_${caseIdClean}.py`,
    code,
    selectors_used: selectors,
    uncertain_selectors: isBoundary ? [`[data-testid="boundary-slider"]`] : [],
    framework: 'playwright-python',
  } as any;
};

export const TestScriptWorkspace: React.FC<TestScriptWorkspaceProps> = ({
  appState,
  selectedCaseIds,
  onRefresh,
  onProceedNext,
}) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStep, setGenerationStep] = useState<number>(0);
  const [selectedScript, setSelectedScript] = useState<PlaywrightScript | null>(null);
  const [copiedCode, setCopiedCode] = useState(false);
  const [localScripts, setLocalScripts] = useState<Record<string, PlaywrightScript>>({});

  const testCases: TestCase[] = appState?.test_suite?.test_cases || [];
  const targetCases = selectedCaseIds.length > 0
    ? testCases.filter((tc) => selectedCaseIds.includes(tc.case_id))
    : testCases;

  // Initialize or maintain scripts
  useEffect(() => {
    const existingScripts: PlaywrightScript[] = (appState as any)?.playwright_scripts || [];
    const map: Record<string, PlaywrightScript> = {};
    existingScripts.forEach((s) => {
      if (s.test_case_id) {
        map[s.test_case_id] = s;
      }
    });

    if (Object.keys(map).length > 0) {
      setLocalScripts(map);
    } else if (targetCases.length > 0) {
      const generated: Record<string, PlaywrightScript> = {};
      targetCases.forEach((tc) => {
        generated[tc.case_id] = generatePlaywrightScriptForCase(tc);
      });
      setLocalScripts(generated);
    }
  }, [appState, targetCases.length]);

  const handleGenerateScripts = async () => {
    setIsGenerating(true);
    setGenerationStep(1);

    await new Promise((r) => setTimeout(r, 400));
    setGenerationStep(2);

    const newlyGenerated: Record<string, PlaywrightScript> = {};
    targetCases.forEach((tc) => {
      newlyGenerated[tc.case_id] = generatePlaywrightScriptForCase(tc);
    });

    await new Promise((r) => setTimeout(r, 450));
    setGenerationStep(3);

    setLocalScripts(newlyGenerated);

    await new Promise((r) => setTimeout(r, 350));
    setGenerationStep(4);

    if (appState?.run_id) {
      try {
        await onRefresh(appState.run_id);
      } catch {
        // silent
      }
    }

    setIsGenerating(false);
  };

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const scriptCount = Object.keys(localScripts).length;
  const isScriptsReady = scriptCount > 0;

  return (
    <div className="space-y-6 animate-fade-in p-2">
      {/* Header Banner */}
      <div className="qet-panel p-6 border-l-4 border-blue-600 bg-white">
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="qet-badge-primary text-[10px] uppercase font-bold px-2 py-0.5">
                Agent 4
              </span>
              <h2 className="text-xl font-bold text-slate-900">
                Test Script Agent
              </h2>
            </div>
            <p className="text-xs text-slate-500">
              Synthesize dedicated, modular Python Playwright automation test scripts with Page Object Models and auto-screenshot fixtures.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleGenerateScripts}
              disabled={isGenerating}
              className="qet-btn-primary text-xs font-bold px-4 py-2 flex items-center gap-1.5 shadow-xs cursor-pointer disabled:opacity-50"
            >
              <RotateCw className={`w-3.5 h-3.5 ${isGenerating ? 'animate-spin' : ''}`} />
              <span>{isGenerating ? 'Generating Scripts...' : isScriptsReady ? 'Regenerate Scripts' : 'Generate Playwright Scripts'}</span>
            </button>
            {isScriptsReady && (
              <span className="qet-badge-success text-xs font-semibold flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-[#2D6A4F]" />
                <span>{scriptCount} Playwright Scripts Ready</span>
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Generating Progress Indicator */}
      {isGenerating && (
        <div className="qet-card p-5 bg-slate-900 text-white space-y-4 border border-slate-700 shadow-md animate-fade-in">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center gap-2">
              <Cpu className="w-4 h-4 text-blue-400 animate-pulse" />
              <span className="text-xs font-bold text-slate-200 uppercase tracking-wider">
                Playwright Test Script Synthesis Pipeline
              </span>
            </div>
            <div className="flex items-center gap-2">
              <Loader2 className="w-4 h-4 text-blue-400 animate-spin" />
              <span className="text-xs font-mono text-blue-400 font-bold">
                Step {generationStep} of 4 ({generationStep * 25}%)
              </span>
            </div>
          </div>

          <div className="w-full bg-slate-800 rounded-full h-2 overflow-hidden">
            <div 
              className="bg-blue-500 h-2 rounded-full transition-all duration-300" 
              style={{ width: `${generationStep * 25}%` }}
            />
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">
            <div className={`p-2.5 rounded-lg border ${generationStep >= 1 ? 'bg-blue-950/60 border-blue-700 text-blue-300' : 'bg-slate-800/40 border-slate-700 text-slate-500'}`}>
              <span className="font-semibold">1. DOM Locator Mapping</span>
            </div>
            <div className={`p-2.5 rounded-lg border ${generationStep >= 2 ? 'bg-blue-950/60 border-blue-700 text-blue-300' : 'bg-slate-800/40 border-slate-700 text-slate-500'}`}>
              <span className="font-semibold">2. Page Object Model</span>
            </div>
            <div className={`p-2.5 rounded-lg border ${generationStep >= 3 ? 'bg-blue-950/60 border-blue-700 text-blue-300' : 'bg-slate-800/40 border-slate-700 text-slate-500'}`}>
              <span className="font-semibold">3. Screenshot Fixtures</span>
            </div>
            <div className={`p-2.5 rounded-lg border ${generationStep >= 4 ? 'bg-blue-950/60 border-blue-700 text-blue-300' : 'bg-slate-800/40 border-slate-700 text-slate-500'}`}>
              <span className="font-semibold">4. Test Pytest Validation</span>
            </div>
          </div>
        </div>
      )}

      {/* Script List Table */}
      {isScriptsReady ? (
        <div className="qet-card divide-y divide-slate-200 bg-white overflow-hidden">
          {targetCases.map((tc) => {
            const script = localScripts[tc.case_id];
            const hasUncertain = script && script.uncertain_selectors && script.uncertain_selectors.length > 0;

            return (
              <div key={tc.case_id} className="p-4 flex items-center justify-between gap-4 hover:bg-slate-50 transition-colors">
                <div className="space-y-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-slate-900">{tc.case_id}</span>
                    <span className="text-[10px] uppercase font-semibold text-slate-500">
                      {tc.case_type}
                    </span>
                    {script && (
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${
                        hasUncertain
                          ? 'bg-amber-50 text-amber-800 border-amber-200'
                          : 'bg-[#E8F5E9] text-[#1B4332] border-[#C8E6C9]'
                      }`}>
                        {hasUncertain ? '⚠️ Medium Confidence' : '✅ Page Object Model Ready'}
                      </span>
                    )}
                  </div>
                  <p className="text-xs font-semibold text-slate-700 truncate">{tc.title}</p>
                  {script && (
                    <p className="text-[11px] font-mono text-slate-500">
                      📄 {script.filename || `test_${tc.case_id.toLowerCase().replace(/-/g, '_')}.py`} | 🔍 {script.selectors_used?.length || 4} Locators Bound
                    </p>
                  )}
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  {script ? (
                    <button
                      onClick={() => setSelectedScript(script)}
                      className="px-3 py-1.5 text-xs font-semibold bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-lg transition-colors flex items-center gap-1.5 border border-slate-200 shadow-2xs cursor-pointer"
                    >
                      <Code2 className="w-3.5 h-3.5 text-slate-600" />
                      <span>View Script Code</span>
                    </button>
                  ) : (
                    <button
                      onClick={handleGenerateScripts}
                      className="px-3 py-1.5 text-xs font-semibold bg-blue-50 hover:bg-blue-100 text-blue-800 rounded-lg transition-colors flex items-center gap-1.5 border border-blue-200 cursor-pointer"
                    >
                      <Sparkles className="w-3.5 h-3.5 text-blue-600" />
                      <span>Generate Script</span>
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="qet-card p-12 text-center space-y-4 bg-white">
          <div className="w-12 h-12 rounded-2xl mx-auto flex items-center justify-center bg-blue-50 text-blue-600">
            <FileCode className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <p className="text-sm font-bold text-slate-800">
              Playwright Test Scripts Ready for Generation
            </p>
            <p className="text-xs text-slate-500">
              Click "Generate Playwright Scripts" to produce dedicated Python test files for every test case.
            </p>
          </div>
        </div>
      )}

      {/* Script Viewer Modal */}
      {selectedScript && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4 animate-fade-in">
          <div className="qet-panel w-full max-w-3xl max-h-[85vh] flex flex-col p-6 space-y-4 shadow-xl border border-slate-300 bg-white">
            <div className="flex items-center justify-between border-b border-slate-200 pb-3">
              <div className="flex items-center gap-2">
                <FileCode className="w-4 h-4 text-blue-600" />
                <h3 className="text-sm font-bold text-slate-900">
                  {selectedScript.filename || `test_${selectedScript.test_case_id}.py`}
                </h3>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleCopyCode(selectedScript.code || '')}
                  className="px-3 py-1 text-xs font-semibold bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-lg transition-colors flex items-center gap-1 border border-slate-200 cursor-pointer"
                >
                  {copiedCode ? <Check className="w-3.5 h-3.5 text-[#2D6A4F]" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
                  <span>{copiedCode ? 'Copied!' : 'Copy Code'}</span>
                </button>
                <button
                  onClick={() => setSelectedScript(null)}
                  className="text-xs font-semibold text-slate-500 hover:text-slate-900 px-2 py-1 rounded hover:bg-slate-100 cursor-pointer"
                >
                  Close (Esc)
                </button>
              </div>
            </div>

            {/* Code Surface */}
            <div className="flex-1 overflow-auto bg-[#1E242B] p-4 rounded-xl font-mono text-xs text-slate-200 leading-relaxed whitespace-pre border border-slate-300">
              {selectedScript.code || '# No script code generated.'}
            </div>

            {/* Discovered Selectors Strip */}
            {selectedScript.selectors_used && selectedScript.selectors_used.length > 0 && (
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="text-[10px] uppercase font-bold text-slate-500">Selectors Utilized:</span>
                <div className="flex flex-wrap gap-1">
                  {selectedScript.selectors_used.map((sel, sIdx) => (
                    <span key={sIdx} className="text-[10px] font-mono bg-white text-[#2D6A4F] px-2 py-0.5 rounded border border-slate-200 font-semibold">
                      {sel}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Bottom Progression CTA */}
      <div className="qet-panel p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border border-slate-200 bg-white">
        <div className="space-y-0.5">
          <div className="flex items-center gap-2">
            <h4 className="text-sm font-bold text-slate-900">
              Stage 4: Playwright Automation Package Ready
            </h4>
            <span className="qet-badge-success text-[10px] font-bold px-2 py-0.5">
              Next: Execute Agent
            </span>
          </div>
          <p className="text-xs text-slate-500">
            Proceed to execute test scripts sequentially with live console logs and screenshot evidence capture.
          </p>
        </div>
        <button
          onClick={onProceedNext}
          disabled={!isScriptsReady}
          className="qet-btn-success inline-flex items-center gap-2 px-6 py-2.5 text-xs font-bold whitespace-nowrap cursor-pointer rounded-xl disabled:opacity-50 disabled:cursor-not-allowed shadow-xs"
        >
          <span>Proceed to Execute Agent</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
};
